### ISSUE TITLE
A major problem with climenu on pypi

### ISSUE THREAD

**Issue by daknuett** [mtik00/mtik00.github.io#1]
I am unable to contact you on any other way,
so I just opened this issue.

I am pretty sure that you forgot to add the actual package in
your package submission on pypi for climenu.

And I am really interested in using this package!

Thank you in advance,
Daniel Knüttel

**Comment by mtik00** [comment]
Sorry, I just saw this.  I imagine the problem is solved.
```
Collecting climenu
  Downloading climenu-1.6.0-py2.py3-none-any.whl
Installing collected packages: climenu
Successfully installed climenu-1.6.0
```

The official repo is here: https://github.com/mtik00/pyclimenu
